<?xml version="1.0" encoding="utf-8"?><Database Name="Calismaa" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Calismaa;Integrated Security=True" SettingsObjectName="LINQ.Properties.Settings" SettingsPropertyName="CalismaaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Album" Member="Albums">
    <Type Name="Album">
      <Column Name="AlbumID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AlbumAdi" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Sanatci" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Tur" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fiyat" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>