//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PerID { get; set; }
        public string PerAd { get; set; }
        public string PerSoyad { get; set; }
        public Nullable<short> BolumID { get; set; }
    }
}
